---
name: PSA Car Controller v3.0
version: v3.0
slug: psacc_v3
description: Control and get information from your PSA car
url: https://github.com/flobz/psa_car_controller
startup: application
boot: auto
init: false
ingress: true
ingress_port: 5000
legacy: true
image: flobz/psa_car_controller
panel_icon: mdi:car
homeassistant: 0.92.0b2
arch:
  - aarch64
  - amd64
  - armhf
auth_api: true
ports:
  5000/tcp: null
ports_description:
  5000/tcp: Web interface (Not required for Ingress)
environment:
  PSACC_PORT: 5000
  PSACC_CONFIG_DIR: /data
options:
  PSACC_OPTIONS: -r --web-conf -c
schema:
  PSACC_OPTIONS: str
